language: cpp
sudo: false
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/

addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test
      
env:
  global:
    - ASM=./nasm-2.13.03/nasm
# fix clang complaining about unused command line args with ccache, see http://peter.eisentraut.org/blog/2014/12/01/ccache-and-clang-part-3/
    - CCACHE_CPP2=yes 
    

cache: ccache

# the anchors element doesn't do anything but itself except define some anchors to be used later as aliases
anchors:
  - &unit_command ./unit-test
  - &uarch_command ./uarch-bench --test-tag=~slow

matrix:
  include:
      # clang-5.0 is the default installed on travis VMs
    - compiler: clang-default
      env: TRUE_CC=clang TRUE_CXX=clang++ CXXFLAGS=-stdlib=libc++
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libc++abi1
            - libc++1
    - compiler: gcc-4.9
      env: TRUE_CC=gcc-4.9 TRUE_CXX=g++-4.9 PIE=
      addons:
        apt:
          sources:
          - *default_sources
          packages:
          - gcc-4.9
          - g++-4.9
    - compiler: gcc-6
      env: TRUE_CC=gcc-6 TRUE_CXX=g++-6
      addons:
        apt:
          sources:
          - *default_sources
          packages:
          - gcc-6
          - g++-6
    - compiler: gcc-6-yasm
      env: TRUE_CC=gcc-6 TRUE_CXX=g++-6 ASM=yasm
      addons:
        apt:
          sources:
          - *default_sources
          packages:
          - gcc-6
          - g++-6
    - compiler: clang-6.0
      env: TRUE_CC=clang-6.0 TRUE_CXX=clang++-6.0
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-6.0
          packages:
          - *default_pacakges
          - clang-6.0
          - clang++-6.0

before_install:
# Travis will set CC and CXX after the env commands specified in the matrix are run, overwriting whatever
# we've specified there, so we need to reset them here. See also https://github.com/travis-ci/travis-ci/issues/6633 . 
  - CC="ccache ${TRUE_CC:-$CC}"
  - CXX="ccache ${TRUE_CXX:-$CXX}"


script:
- set -e && echo "CC is ${CC}, CXX is ${CXX}" && ${CC} --version && ${CXX} --version
- make
- ./avx-turbo
